services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://test:test@realty:5432/postgres?sslmode=disable
      - REDIS_ADDR=redis:6379

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  migrate:
    image: migrate/migrate:latest
    command: [
      "-path", "/migrations",
      "-database", "postgres://test:test@realty:5432/postgres?sslmode=disable",
      "up"
    ]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db

volumes:
  db_data:
  redis_data:
