server:
  host: localhost
  port: 4000
postgres:
  host: db
  port: 5432
  dbname: realty
  user: test
  password: test
logger:
  path: logs
  filename: logs.json
  level: info
jwt:
  secret: secret
  accessTokenTime: 60 
  refreshTokenTime: 86400
